### PR TITLE
signout wont blow up anymore

### PR DESCRIPTION
**Pull request by frimpongopoku**
### Related Ticket: https://github.com/massenergize/frontend-portal/issues/1202#event-9417779589 

- [X] SIgnout on profile page wont blow up anymore 

## DEMO 

 

https://github.com/massenergize/frontend-portal/assets/26961591/86907aa5-a339-453d-a17a-32abfdd6f4b0

### CODE REVIEW

**Review by BradHN1 — CHANGES_REQUESTED** [review]
This works, but I think in the case the user signs out from profile page, it should move to the Home page.  Any other page, signing out should keep you on that page.

**Review by BradHN1 — APPROVED** [review]
LGTM

**Comment by BradHN1** [comment]
@frimpongopoku - did you address the comment I made about sending you to the home page if you signout from the profile page?

**Comment by frimpongopoku** [comment]
@BradHN1  I have pushed the requested changes 

- [X] If you signout on any other page, you stay on that page. But if you signout from the profile page, you are taken to the homepage. 

## See Here 

https://github.com/massenergize/frontend-portal/assets/26961591/9b6e9984-2343-43ac-8844-aa9b0c490304

**Review by abdullai-t — APPROVED** [review]
LGTM ✅

**Comment by abdullai-t** [comment]
@frimpongopoku, does it work on the preference page ?

**Comment by frimpongopoku** [comment]
yhup. Any router that has /profile in it will behave like that.

**Pull request merged**
