### PR TITLE
Issue 413 - Can't sign in through Google if account doesn't exist

### PR DESCRIPTION
**Pull request by BradHN1**

### CODE REVIEW

**Comment by BradHN1** [comment]
Added Frimpong as a reviewer though the main question about reg_protocol may need answer from Sam

**Comment by frimpongopoku** [comment]
Hi @BradHN1  what is the question you are asking again...? And what is the scenario for the bug this PR is fixing???

**Comment by BradHN1** [comment]
The bug (issue 413) was that if a person tries to sign-in with Google without having registered, it fails with an infinite spinner.  See the issue ticket for details.  I tracked it down and made a solution involving reg_protocol but I don't completely understand how that works.

**Comment by frimpongopoku** [comment]
Ooo I seee, great! You actually went in the right direction 😂😂🙌🏾.

I think i made a brief description of how reg_protocol works at the bottom
of RegistrationForm.js. Try and see if you will understand things from
there. If you dont, I will explain again in ur dms😂

**Review by Opoku-Agyemang — APPROVED** [review]

**Pull request merged**
