### PR TITLE
User Settings Page Bug Fix

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights

This PR contains:
- A quick fix for the broken settings page in canary as suggested by @frimpongopoku in [#1098](https://github.com/massenergize/frontend-portal/issues/1098) 
- An implementation of hiding the settings page behind a feature flag as suggested by @Davidjwkinghorn 
- A patch to the `Feature` component to cater for user specific feature flags
#### Details (Give details about what this PR accomplishes, include any screenshots etc)
Screenshot 2022-08-16 at 11 10 55 PM
Screenshot 2022-08-16 at 11 11 33 PM

#### Requirements (place an `x` in each `[ ]`)
* [x] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [x] I've given my PR a meaningful title.
* [x] I linked this PR to the relevant issue.
* [x] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [x] I moved the linked issue to "QA Verification" now that it is ready to merge.

### CODE REVIEW

**Comment by Davidjwkinghorn** [comment]
I tried to deploy this straight to canary for testing. The deploy failed, not sure why this is breaking. It seems to be a sentry dependency issue.
```3:11:06 PM: Build ready to start
3:11:08 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
3:11:08 PM: build-image tag: v4.10.1
3:11:08 PM: buildbot version: 4cffa5dc84445a450e8be6f710e2498d87994fae
3:11:08 PM: Fetching cached dependencies
3:11:08 PM: Starting to download cache of 266.5MB
3:11:11 PM: Finished downloading cache in 2.765243425s
3:11:11 PM: Starting to extract cache
3:11:17 PM: Finished extracting cache in 6.758693091s
3:11:17 PM: Finished fetching cache in 9.615001975s
3:11:17 PM: Starting to prepare the repo for build
3:11:18 PM: Preparing Git Reference refs/heads/canary
3:11:18 PM: Parsing package.json dependencies
3:11:19 PM: Starting build script
3:11:19 PM: Installing dependencies
3:11:19 PM: Python version set to 3.8
3:11:19 PM: Started restoring cached node version
3:11:20 PM: Finished restoring cached node version
3:11:20 PM: v14.17.5 is already installed.
3:11:21 PM: Now using node v14.17.5 (npm v6.14.14)
3:11:21 PM: Started restoring cached build plugins
3:11:21 PM: Finished restoring cached build plugins
3:11:21 PM: Attempting ruby version 2.7.2, read from environment
3:11:21 PM: Using ruby version 2.7.2
3:11:22 PM: Using PHP version 8.0
3:11:22 PM: No npm workspaces detected
3:11:22 PM: Started restoring cached node modules
3:11:22 PM: Finished restoring cached node modules
3:11:22 PM: Started restoring cached go cache
3:11:22 PM: Finished restoring cached go cache
3:11:22 PM: Installing Go version 1.16.5 (requested 1.16.5)
3:11:26 PM: unset GOOS;
3:11:26 PM: unset GOARCH;
3:11:26 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64';
3:11:26 PM: export PATH="/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:${PATH}";
3:11:26 PM: go version >&2;
3:11:26 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.16.5.linux.amd64.env"
3:11:26 PM: go version go1.16.5 linux/amd64
3:11:26 PM: Installing missing commands
3:11:26 PM: Verify run directory
3:11:27 PM: ​
3:11:27 PM: ────────────────────────────────────────────────────────────────
3:11:27 PM:   Netlify Build                                                 
3:11:27 PM: ────────────────────────────────────────────────────────────────
3:11:27 PM: ​
3:11:27 PM: ❯ Version
3:11:27 PM:   @netlify/build 27.11.5
3:11:27 PM: ​
3:11:27 PM: ❯ Flags
3:11:27 PM:   baseRelDir: true
3:11:27 PM:   buildId: 62fd3d14cc55cd00084d8848
3:11:27 PM:   deployId: 62fd3d14cc55cd00084d884a
3:11:27 PM: ​
3:11:27 PM: ❯ Current directory
3:11:27 PM:   /opt/build/repo
3:11:27 PM: ​
3:11:27 PM: ❯ Config file
3:11:27 PM:   No config file was defined: using default values.
3:11:27 PM: ​
3:11:27 PM: ❯ Context
3:11:27 PM:   production
3:11:27 PM: ​
3:11:27 PM: ────────────────────────────────────────────────────────────────
3:11:27 PM:   1. Build command from Netlify app                             
3:11:27 PM: ────────────────────────────────────────────────────────────────
3:11:27 PM: ​
3:11:27 PM: $ make init && make build
3:11:27 PM: npm install
3:11:28 PM: > massenergize_admin_site@2.0.0 preinstall /opt/build/repo
3:11:28 PM: > npm run npmcheckversion
3:11:28 PM: > massenergize_admin_site@2.0.0 npmcheckversion /opt/build/repo
3:11:28 PM: > node ./internals/scripts/npmcheckversion.js
3:11:35 PM: npm ERR! code ETARGET
3:11:35 PM: npm ERR! notarget No matching version found for @sentry/hub@7.11.1.
3:11:35 PM: npm ERR! notarget In most cases you or one of your dependencies are requesting
3:11:35 PM: npm ERR! notarget a package version that doesn't exist.npm ERR! notarget
3:11:35 PM: npm ERR! notarget It was specified as a dependency of '@sentry/tracing'
3:11:35 PM: npm ERR! notarget
3:11:35 PM: npm ERR! A complete log of this run can be found in:
3:11:35 PM: npm ERR!     /opt/buildhome/.npm/_logs/2022-08-17T19_11_35_523Z-debug.log
3:11:35 PM: make: *** [Makefile:2: init] Error 1
3:11:35 PM: ​
3:11:35 PM: ────────────────────────────────────────────────────────────────
3:11:35 PM:   "build.command" failed                                        
3:11:35 PM: ────────────────────────────────────────────────────────────────
3:11:35 PM: ​
3:11:35 PM:   Error message
3:11:35 PM:   Command failed with exit code 2: make init && make build (https://ntl.fyi/exit-code-2)
3:11:35 PM: ​
3:11:35 PM:   Error location
3:11:35 PM:   In Build command from Netlify app:
3:11:35 PM:   make init && make build
3:11:35 PM: ​
3:11:35 PM:   Resolved config
3:11:35 PM:   build:
3:11:35 PM:     command: make init && make build
3:11:35 PM:     commandOrigin: ui
3:11:35 PM:     environment:
3:11:35 PM:       - NODE_VERSION
3:11:35 PM:       - NPM_VERSION
3:11:35 PM:       - PYTHON_VERSION
3:11:35 PM:       - REACT_APP_DOC_API_KEY
3:11:35 PM:       - REACT_APP_SENTRY_PROD_DSN
3:11:35 PM:       - REACT_APP_TINY_MCE_KEY
3:11:35 PM:     publish: /opt/build/repo/build
3:11:35 PM:     publishOrigin: ui
3:11:36 PM: Caching artifacts
3:11:36 PM: Started saving node modules
3:11:36 PM: Finished saving node modules
3:11:36 PM: Started saving build plugins
3:11:36 PM: Finished saving build plugins
3:11:36 PM: Started saving pip cache
3:11:36 PM: Finished saving pip cache
3:11:36 PM: Started saving emacs cask dependencies
3:11:36 PM: Finished saving emacs cask dependencies
3:11:36 PM: Started saving maven dependencies
3:11:36 PM: Finished saving maven dependencies
3:11:36 PM: Started saving boot dependencies
3:11:36 PM: Finished saving boot dependencies
3:11:36 PM: Started saving rust rustup cache
3:11:36 PM: Finished saving rust rustup cache
3:11:36 PM: Started saving go dependencies
3:11:36 PM: Finished saving go dependencies
3:11:36 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
3:11:36 PM: Creating deploy upload records
3:11:36 PM: Failing build: Failed to build site
3:11:36 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
3:11:36 PM: Finished processing build request in 28.358512207s```

**Comment by Davidjwkinghorn** [comment]
I can revisit this tomorrow.

**Comment by Davidjwkinghorn** [comment]
I've been able to get a deploy out, but I'm just noticing that I was testing canary when I meant to be testing this. Now I've deployed, I can see something is broken. Nothing loads anymore, it's just a blank, white screen. Can you give this another look?

**Comment by abdullai-t** [comment]
sure

**Comment by Davidjwkinghorn** [comment]
This has been resolved, should be fine.

**Pull request closed without merging**
