### PR TITLE
Submitted Contents Add Btn Repositioned

### PR DESCRIPTION
**Pull request by abdullai-t**
#### Changes
- [x] Made the user-submitted content buttons show even when users are not authenticated
- [x] On PC, the button will show at the top right corner of the search and filter bar.
- [x] On Mobile, the button will show on the same line as the search bar

#### Demo
https://github.com/massenergize/frontend-portal/assets/42780120/718f1999-0972-48e6-aad3-43fe2315fe99

### CODE REVIEW

**Comment by BradHN1** [comment]
Under the condition that the feature flags are not set, the page title and subtitle are not centered properly:
Screenshot 2023-06-17 at 7 09 33 AM

**Comment by BradHN1** [comment]
In the condition that the optional sub-title is not set, the title should be vertically aligned with the button, not have as large a gap below it:
Screenshot 2023-06-17 at 7 16 40 AM

**Comment by frimpongopoku** [comment]
Also @abdullai-t (this is Priority 3) but the padding on the button in PC mode is OFF.  Look at the  padding on the sign in button and that of the button you added... 🌚 
Screenshot 2023-06-19 at 05 37 39

**Comment by abdullai-t** [comment]
@BradHN1, @frimpongopoku , @kaatvds. Here is an update

https://github.com/massenergize/frontend-portal/assets/42780120/8cc7ad9e-fafb-4f52-ab65-f55963c67ba9

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
