### PR TITLE
Optional add password to passwordless

### PR DESCRIPTION
**Pull request by frimpongopoku**
- [X] Now, users that use password-less can add a password to their account anytime.
Screenshot 2022-03-16 at 16 15 24

- [X] Deleting account for password-less user has now moved here as well. 
Screenshot 2022-03-16 at 16 15 15

**NB: This page is only valid for users who use ONLY password-less authentication.**
If a user uses multiple authentication methods with the same email, they wont need to come to this page for anything.

### CODE REVIEW

**Comment by Davidjwkinghorn** [comment]
Some feedback on the user flow: 
If this is the user flow we're using, It's not obvious to a user that they have to click the link to be sent an email to verify it's really them **before** adding password sign on or deleting their profile. I know it says so, but the "Add a Password" and "Delete My Account" buttons should be hidden before the user is verified to communicate this nonverbally.

I think it's best to send the email to verify after the user has chosen what action they wish to perform.
Instead of:
1. Click to send verification email
2. Click link in email to verify
3. Chose to add password or delete profile
4. Confirm

It should be either:
1. Chose to add password or delete profile 
2. Confirm (We send a link on confirmation and tell the user)
3. Click link in email to verify

OR

1. Chose to add password or delete profile
2. We send a link on confirmation and tell the user (Click link in email to verify) 
3. Confirm

**Comment by frimpongopoku** [comment]
> Some feedback on the user flow: If this is the user flow we're using, It's not obvious to a user that they have to click the link to be sent an email to verify it's really them **before** adding password sign on or deleting their profile. I know it says so, but the "Add a Password" and "Delete My Account" buttons should be hidden before the user is verified to communicate this nonverbally.
> 
> I think it's best to send the email to verify after the user has chosen what action they wish to perform. Instead of:
> 
> 1. Click to send verification email
> 2. Click link in email to verify
> 3. Chose to add password or delete profile
> 4. Confirm
> 
> It should be either:
> 
> 1. Chose to add password or delete profile
> 2. Confirm (We send a link on confirmation and tell the user)
> 3. Click link in email to verify
> 
> OR
> 
> 1. Chose to add password or delete profile
> 2. We send a link on confirmation and tell the user (Click link in email to verify)
> 3. Confirm

@Davidjwkinghorn true true, true! 🔥
On it! 

Also, while we are still on "ease"  and preventing mistakes on the users's side, we should probably remove any extra steps. Like, "choosing" anything, since all the current options have the same requirements.
That said, we could keep the current process, and just deactivate the functionalities, until the user uses the link we send to their emails, as you suggested. What do you think?

**Comment by frimpongopoku** [comment]
- [X] Tabs are now deactivated like this when users have not used the link from their emails.

Screenshot 2022-03-17 at 10 07 56

- [X] This is after they use the link from their emails 
Screenshot 2022-03-17 at 10 10 10

@Davidjwkinghorn

**Comment by Davidjwkinghorn** [comment]
> Also, while we are still on "ease" and preventing mistakes on the users's side, we should probably remove any extra steps. Like, "choosing" anything, since all the current options have the same requirements.
> That said, we could keep the current process, and just deactivate the functionalities, until the user uses the link we send to their emails, as you suggested. What do you think?

That's looking good!

We might want to have a discussion at the software meeting tomorrow about user flows for these two actions. I'm realizing now that we might not want to reduce the number of steps it takes to delete a profile by too much. That way it's less likely to be done on accident.

**Comment by Davidjwkinghorn** [comment]
A few issues I came across while testing:
1. Profile failed to delete `POST /api/users.delete HTTP/1.1" 403 62`
2. After deleting a password-less profile the page failed to redirect
3. Following the failed redirect I was logged out, but on attempting to try to delete the profile again I got the error below. This probably won't be a problem as long as this page isn't reachable to users who aren't logged in.
[Cooler Concord.pdf](https://github.com/massenergize/frontend-portal/files/8289438/Cooler.Concord.pdf)

**Comment by Davidjwkinghorn** [comment]
> A few issues I came across while testing:
> 
> 1. Profile failed to delete `Forbidden: /api/users.delete  POST /api/users.delete HTTP/1.1" 403 62`
> 2. After deleting a password-less profile the page failed to redirect
> 3. Following the failed redirect I was logged out, but on attempting to try to delete the profile again I got the error below. This probably won't be a problem as long as this page isn't reachable to users who aren't logged in.
>    [Cooler Concord.pdf](https://github.com/massenergize/frontend-portal/files/8289438/Cooler.Concord.pdf)

This issue appears to be outside of the scope of this PR. Should be good to go.

**Review by Davidjwkinghorn — APPROVED** [review]
LGTM

**Pull request merged**
