### PR TITLE
Testimonials - no anonymous, no tags, allow upload photos

### PR DESCRIPTION
**Pull request by BradHN1**
Frontend portal issues #141, #208, #239
Uploading testimonials is currently broken since apiCallWithMedia doesn't seem to work.

### CODE REVIEW

**Comment by BradHN1** [comment]
Need to fix the ApiCallWithMedia before merging this.

**Comment by Pongo1** [comment]
So most testimonials showing "Unknown user" is more preferable to "Anonymous"??  Maybe we should actually create a check that will allow us to know when we are dealing with a testimonial that was created before the "anonymous" feature came on board, so we wont even show that green label, and only show the green labelled "anonymous" or user's preferred name, for testimonials that  users voluntarily provided one of the two... ? What do you think ❓ @BradHN1

**Comment by BradHN1** [comment]
Testimonials will list the preferred name, and shouldn’t show up as “anonymous” or “unknown user”.  This was a decision by our core team some time back.  Testimonials without a name are useless.

++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)

**Comment by Pongo1** [comment]
So now its "preferred name" or nothing right??? Beautiful ✨  even better 💚

**Pull request merged**
