### PR TITLE
Service providers page works with url filters as well

### PR DESCRIPTION
**Pull request by frimpongopoku**

### CODE REVIEW

**Review by Opoku-Agyemang — CHANGES_REQUESTED** [review]
please add screenshots to your PR and some description

**Comment by frimpongopoku** [comment]
Made a long PR earlier with more description. This is just a part I forgot to add 🤣 
Here it is again: 

Now adding filters populates the address bar with the selected filters. So, we can just share a link that already has pre-selected filters, and the site will load and show the user only the filtered content right away. This has been implemented  on `Actions, Events, Testimonials` already, this PR is the implementation for service providers page.

Screenshot 2022-02-21 at 10 32 10

**Comment by frimpongopoku** [comment]
@Opoku-Agyemang e do?

**Review by Opoku-Agyemang — APPROVED** [review]
LGTM ✅

**Pull request merged**
