### PR TITLE
Mostly tickets #357, #363, #367 

### PR DESCRIPTION
**Pull request by frimpongopoku**

### CODE REVIEW

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Having trouble with the dev API, so can't test everything but here is what I noticed testing locally:
* on #367 now clicking on the photo works, but not clicking on the title.  I suggest moving the </Link> down to below the next </div> to include the action title.  (Also I think make action title 18 point font with padding of "0px 10px" is more readable;
* on #357, on the all action pages I still see the most recent action i did go to the bottom of the list, and it should be at the top.

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Looks good - with one suggested change and one question:
For users not signed in, the ToDo and Done buttons are totally different size.  Can't they also be MEButton or have the same size and shape as the Info button?
Screen Shot 2020-10-28 at 8 42 50 AM

**Comment by frimpongopoku** [comment]
LOOOOOL!. This is funny 🤣  🤣 . I will work on that ASAP. 
Also, the reason I am not bothering to use MEButtons in some places is because there is no "disabled" version of the MEButton I made. To make that, I would just have to make a css class, that will force the buttons to show some different styles and stuff when disabled. Which is the same is editing the old classes on the already existing button. While using MEButtons everywhere is standard and cleaner, playing  with the MEButtons at this stage while it is appearing in so many different places is scary, its not a good idea, at least, now is not the time🤣. That is why I am trying not to touch anything in MEButtons, and I'm just tinkering with the old buttons that are already there. 

When we get the right picture we want from the old buttons, I will make different states of the MEButtons that will just switch props and display any kind of designs we want. ( Sometime after our working state has been deployed to prod) @BradHN1

**Review by BradHN1 — APPROVED** [review]
Better, will deploy to dev first

**Pull request merged**
