### PR TITLE
Issues 686, 687 - Donut statistics calculation and visual improvements

### PR DESCRIPTION
**Pull request by BradHN1**
Donut statistics calculation and visual improvement

### CODE REVIEW

**Comment by BradHN1** [comment]
Here is a screenshot of the home page donut improvements:
Screen Shot 2021-09-24 at 8 55 18 AM

**Comment by BradHN1** [comment]
Here is the old version, which many people have complained is not easily understandable by new users:
Screen Shot 2021-09-24 at 9 27 39 AM

**Comment by BradHN1** [comment]
In the two screenshots above, the reason the numbers don't agree on households and actions is that I didn't zero out the initial values for households and actions as I should have.  Now the new version data are consistent with the old:
Screen Shot 2021-09-24 at 9 35 19 AM

**Review by Opoku-Agyemang — APPROVED** [review]
Oh this is really cool!

**Pull request merged**
