### PR TITLE
Issue 628: Story preferred name by default

### PR DESCRIPTION
**Pull request by BradHN1**
Fix the different views of testimonials to all show the preferred_name entered by the testimonial writer.

No anonymous testimonials.

Default the preferred name in the testimonial form to be the users preferred name
Also add the share buttons to the one testimonial page

### CODE REVIEW

**Comment by BradHN1** [comment]
@frimpongopoku - please check that the code I commented out is not needed.  Seemed to be a number of legacy things in there.

**Review by Opoku-Agyemang — CHANGES_REQUESTED** [review]
Can i see an image of what was there before and the changes now?
Also can your remove all the commented out code?

**Comment by BradHN1** [comment]
Existing code, on prod shows the testimonials are listed with different names in the side-list and main list:
Screen Shot 2021-11-03 at 4 35 46 PM


Here is the new image:
Screen Shot 2021-11-03 at 4 34 54 PM


I left the commented code in so Frimpong could check that it is ok to remove it.  I’ll remove it once he gives that review, but in my mind it is even worse to have obsolete, unused code mixed in with active code.

**Review by sopokuagyemang — APPROVED** [review]

**Review by frimpongopoku — APPROVED** [review]
I checked, the modal isnt in use anymore so I removed them, and fixed the conflicts. 

LGTM

**Pull request merged**
