### PR TITLE
Pongo new development

### PR DESCRIPTION
**Pull request by frimpongopoku**
Image cropper is not forced on users now. Image is also resized on the fly, even without cropping. Tickets (#415 , #425, #423)

### CODE REVIEW

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Improved cropping process.  One complaint is shown in the picture below.  I choose the image, say I want to do cropping, then the modal with the image to crop is really small.  For cropping we need the image to be large since it makes it possible to see the selection you are making.,
Screen Shot 2020-11-02 at 7 59 51 AM

Also - issue 425 is not critical, posed as a question.  Please don't add new functionality at this point...  Ok this time but let's focus on the critical issues.

**Comment by BradHN1** [comment]
@frimpongopoku - can you make the crop modal have a picture at least as large as the one in the background?

**Comment by frimpongopoku** [comment]
Ooo the modal is actually not small on my end, loool😂. So I will check
what’s happening ASAP.

Also, the only critical left for me, is the password thingy, which I have
been asking questions about in Sam’s dms. They havent been answered yet, so
i just thought i will chip in that ticket in this PR, since it was easy
anyway. 👍🏾

**Review by BradHN1 — APPROVED** [review]
Looks good, works fine!

**Pull request merged**
