### PR TITLE
More random fixes

### LINKED ISSUE #940: Ignore and remove whitespace preceding or following email addresses when we validate them for guest sign in.
I was given a message that I wasn't using a valid email address, but I was. After some digging the cause turned out to be some whitespace my phone had put in when it autofilled my email address. We should ignore and strip whitespace before and after the email address for guest sign in.

### PR DESCRIPTION
**Pull request by frimpongopoku**
- [X] Worked on #936  I am not sure what the expectations were on this ticket, but what do we think of this? 
Used to cover half the screen like this: 
Screenshot 2022-04-22 at 09 37 29

But now its like this: 
Screenshot 2022-04-22 at 10 06 32

This has also been fixed #940 
- [X] Whitespace in browser autofilling wont mess with the emails anymore.

- [X] #941 Added the button to the top only on phone mode. 
Screenshot 2022-04-22 at 13 47 01

- [X] Also implemented the enhancements on this ticket #948. 
I am not sure about about the "sticking" part though, so I have not implemented it yet. I thought we were being cautious of how we used the screen real estate?
This is how it looks now. What do we think? Should I still make it stick?
Screenshot 2022-04-22 at 13 58 26

### CODE REVIEW

**Comment by Davidjwkinghorn** [comment]
The screenshots are looking great! I'll do a code review and some testing and then we can get this merged.

**Comment by Davidjwkinghorn** [comment]
In my testing I came across a few issues

I fixed this first one where we validate the email address.
Screen Shot 2022-04-22 at 10 33 49 AM

Not sure if this one is just in this branch or if it exists in prod. On the profile page the cards don't display correctly at some aspect ratios.
Screen Shot 2022-04-22 at 10 52 26 AM

Guest users don't see the mobile action page changes in this PR.
Screen Shot 2022-04-22 at 10 52 54 AM

Numbers show up as infinity when I run this. This could just be an issue with my environment, though. Zero shows up as NaN (Not a Number).
Screen Shot 2022-04-22 at 10 53 30 AM

**Comment by Davidjwkinghorn** [comment]
> Screen Shot 2022-04-22 at 10 52 26 AM

I have confirmed this is also an issue prod, so not this PR.

**Comment by frimpongopoku** [comment]
You were not seeing the action stats on mobile because you had not added anything to done, or todo. Also what happened before you got the NAN and Infinity? I would like to replicate that and fix.

**Comment by Davidjwkinghorn** [comment]
> You were not seeing the action stats on mobile because you had not added anything to done, or todo. Also what happened before you got the NAN and Infinity? I would like to replicate that and fix.

Okay I see. It only shows up once you start interacting with actions.

Here's a couple videos of me trying a few things. I hope it helps. I'm currently running the api in development if that makes a difference. I'll also verify that my database migrations are up to date just in case.
https://user-images.githubusercontent.com/15150372/164755478-f6056ff1-1488-45f4-8687-e7c5fc041d70.mov

https://user-images.githubusercontent.com/15150372/164755712-cfc24a58-9b24-4aa8-82b8-6a8d0f4d500c.mov

**Comment by Davidjwkinghorn** [comment]
I'll also add that I'm running everything locally

**Comment by Davidjwkinghorn** [comment]
The issue here might have something to do with the fact that there are no options for carbon equivalencies on my profile. Most recently I've been using the canary DB so I should have options for that, but I don't.
Screen Shot 2022-04-22 at 12 53 15 PM

**Comment by Davidjwkinghorn** [comment]
@BradHN1 I think we could merge this to dev and canary and see if it's still an issue. It's not that critical and we could always roll back to a previous commit if we had to.

**Review by Davidjwkinghorn — APPROVED** [review]
Merging to test in dev and canary.

**Comment by Davidjwkinghorn** [comment]
Looks like everything is working fine on canary.

**Pull request merged**
