### PR TITLE
Bhn fixes

### PR DESCRIPTION
**Pull request by BradHN1**
Several fixes: issues 458, 468, 475, 478
Test Facebook login w/ new app id

### CODE REVIEW

**Comment by frimpongopoku** [comment]
Hi @BradHN1 , Currently cant sign in or register with facebook, unless my fb account is noted as an admin on the facebook developer portal. 

Got the error below
Screenshot 2021-01-08 at 16 22 42

**Comment by BradHN1** [comment]
Hi @frimpongopoku I added you and Sam as admins on the app.  Hope that helps

**Comment by frimpongopoku** [comment]
> Hi @frimpongopoku I added you and Sam as admins on the app. Hope that helps

Great 🔥

**Comment by frimpongopoku** [comment]
I have pulled all your changes into a different branch and added a few simple tweaks

**Pull request closed without merging**
