### PR TITLE
overlay will no show on mobile mode

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights
On mobile, the tooltip on the content submission button covers some part of the login modal. This Pr simply removes the tooltip on mobile view
#### Details (Give details about what this PR accomplishes, include any screenshots etc)

https://github.com/massenergize/frontend-portal/assets/42780120/882a7a96-8ad8-4c62-8794-33ea87abf40d

### CODE REVIEW

**Review by BradHN1 — APPROVED** [review]
LGTM - test on dev

**Comment by BradHN1** [comment]
There is a conflict in AddButton.js.  Could you resolve that?  I did that on a previous PR and wasn't sure I got it right.

**Comment by abdullai-t** [comment]
> There is a conflict in AddButton.js. Could you resolve that? I did that on a previous PR and wasn't sure I got it right.

Done

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
