### PR TITLE
Image Preview On Selection + Cropping In Form Generator

### PR DESCRIPTION
**Pull request by frimpongopoku**
Advance MEFileChooser Component. User is forced to crop their image, so it can be resized and made smaller, and they are shown a preview afterwards. 
Removing image, after selection is also allowed this time 🤣 

❗ **YOU WILL NEED TO NPM INSTALL**

### CODE REVIEW

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Please make changes according to issue 393: Testimonial Image Preview and Cropping

**Comment by frimpongopoku** [comment]
Hi @BradHN1 , it is because of huge images that is why we introducing the cropping feature in the first place. No matter the size of the image, the users will be forced to crop. And when they do crop, it will be resized to a really small size that will upload faster and make the whole process smoother. But I will add the warning anyway -- just in case, as described in (#393).

**Comment by BradHN1** [comment]
Please do it as I specified

**Comment by frimpongopoku** [comment]
Okay sir..... 🤣 🤣

**Review by BradHN1 — APPROVED** [review]
Looks good.
There are some minor changes to the way this should work.  Separate ticket.

**Pull request merged**
