### PR TITLE
Code for issue 963

### PR DESCRIPTION
**Pull request by dim505**
I was able to figure out a way to reliably parse the HTML. Instead of doing it via regex I am allowing the browser to do the work. Please let me know if this is something you would consider.

### CODE REVIEW

**Comment by dim505** [comment]
Screenshot from 2022-05-27 17-02-08

**Comment by BradHN1** [comment]
@dim505 - a PR labeled as "Draft" implies not ready to review.  I'll change that but in the future can you take it off draft when you want us to move forward with it?  Thanks

**Comment by frimpongopoku** [comment]
It looks like the HTML is displaying quite nicely 🔥 👯‍♂️   @dim505. Do you mind sharing how this method is more advantageous than react's default `dangerouslySetHTML` field we have been using? 🤔

**Comment by dim505** [comment]
@frimpongopoku honestly I haven't really looked into it. It was another solution that I came across that allowed me to reliably parse the HTML so I could access the text and shorten it.

**Comment by Davidjwkinghorn** [comment]
> It looks like the HTML is displaying quite nicely 🔥 👯‍♂️ @dim505. Do you mind sharing how this method is more advantageous than react's default `dangerouslySetHTML` field we have been using? 🤔

I could be wrong, but I think `dangerouslySetHTML` can introduce security vulnerabilities. We never want to give any users (admin or not) the chance to inject code that we execute without sanitizing it first. There are some third party tools that can do this, but I'm guessing `dangerouslySetHTML` does not.

**Comment by Davidjwkinghorn** [comment]
@dim505 there are two branches labeled for issue 963. I'm assuming this one (`FE_963`) is the one I need to test and merge. Will the other one (`Dmitriy_FE_963`) need to be merged too, does it need more work, or are those changes that will be discarded?

**Comment by Davidjwkinghorn** [comment]
What's the best way to test this? I haven't been able to reproduce this issue on the `development` branch. I definitely haven't seen the issue on this branch.

**Comment by dim505** [comment]
@Davidjwkinghorn

This is the area I fixed

Screenshot from 2022-06-09 16-39-29

**Comment by dim505** [comment]
look under the testimonials tab

**Review by Davidjwkinghorn — APPROVED** [review]
Was able to reproduce the issue on dev and confirm this fixes that. LGTM.

**Pull request merged**
