### PR TITLE
Sticky sidebar on actions page

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights
Made the sidebar displaying done and todo actions stats fixed on the page
#### Details (Give details about what this PR accomplishes, include any screenshots etc)

https://user-images.githubusercontent.com/42780120/231113658-f722ed32-95ce-4608-bf9b-9f93b16b39f2.mp4

#### Requirements (place an `x` in each `[ ]`)
* [ ] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [ ] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

### CODE REVIEW

**Comment by BradHN1** [comment]
On certain screen sizes, tthere might be some overlap:
Screenshot 2023-04-11 at 9 57 13 AM

**Comment by abdullai-t** [comment]
https://user-images.githubusercontent.com/42780120/231429069-894b2af1-2372-4fd0-8d47-0706bbcb37b4.mp4

**Comment by BradHN1** [comment]
@abdullai-t one minor issue: The Title and Subtitle should be centered above the Actions section, and not extend beyond that.  See the figure:
Screenshot 2023-04-12 at 3 50 15 PM

So text shouldn't extend beyond the orange lines.

**Comment by abdullai-t** [comment]
Screenshot 2023-04-13 at 10 25 36 AM

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
