### PR TITLE
1102 - Eliminate guest option completely if feature switched off

### PR DESCRIPTION
**Pull request by BradHN1**

### CODE REVIEW

**Comment by abdullai-t** [comment]
@BradHN1 - from the changes you made, already existing guest users from communities that have disabled guest sign in wouldn't be able to sign in to their guest accounts

**Review by abdullai-t — APPROVED** [review]
LGTM

**Comment by frimpongopoku** [comment]
@BradHN1  that means  old guest users of the community that has just disabled guest mode will not be able to sign... is that the plan? 🤔

**Comment by BradHN1** [comment]
They can sign in with no password, and their profile would become a standard profile.  If they took any actions they would be counted.

**Comment by frimpongopoku** [comment]
> They can sign in with no password, and their profile would become a standard profile. If they took any actions they would be counted.
> […](#)
> Sent from my iPhone
> On Aug 20, 2022, at 3:09 AM, Frimpong Opoku Agyemang ***@***.***> wrote: ﻿ @BradHN1 that means old guest users of the community that has just disabled guest mode will not be able to sign... is that the plan? 🤔 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

I see, so will guests know this somehow 🤔 ? Or how should we let them know?

**Comment by Davidjwkinghorn** [comment]
It's definitely awkward for us to not say anything at this point, specifically regarding guest users. In future we'd roll our features with the feature flag active from the start, but since we already have a bunch of guest user profiles we need to tell them to make a full profile for communities with guest users disabled. 

If guest sign in is disabled for a community we can say "Guest sign in is no longer available for this community, please create a profile to continue. We'd love to see you again." or something to that effect. We shouldn't allow them to still sign in as a guest at all if it's disabled.

**Pull request merged**
