### PR TITLE
Impact Page Data selection

### PR DESCRIPTION
**Pull request by BradHN1**
and a couple other very minor fixes

### CODE REVIEW

**Comment by frimpongopoku** [comment]
Hi @BradHN1  👯 👯‍♂️ 
The code looks good to me, but I am not sure what I am supposed to be looking at here... 🤔. 
Whats happening on impact page? 
Are these aesthetic changes? A picture would be great 😅 
Or tweaks to sync with new backend changes? 

**Aside all, testimonials page also crashes in this PR**

**Comment by BradHN1** [comment]
There are no visual changes to the graphs, except that the Cadmins have selected which data will be included in them.
This is the new explanation box:
IMG_3933

**Comment by BradHN1** [comment]
I don't see the testimonial crash running locally on my computer.  Can you submit a ticket for that with the javascript console?  Or if you can figure out the problem fix it.  That may be related to Dmitriy's changes?

**Comment by frimpongopoku** [comment]
ooo okay, noted. It all looks good to me though. Except testimonials crashes with the preview on netlify and currently deployed dev, not locally.

I will create  a ticket for that, and investigate that one then.

**Review by frimpongopoku — APPROVED** [review]

**Pull request merged**
