### PR TITLE
Pongo new development

### PR DESCRIPTION
**Pull request by frimpongopoku**
Testimonials on vendor individual page and action tabs display testimonial images if available, or the green bulb default image if no image is uploaded. 

Service Provide cards have been switched to previous design/

### CODE REVIEW

**Review by BradHN1 — APPROVED** [review]
Looks good.
Sam gets on my case about leaving in the commented out code.

Note to self - we need to get rid of the picture of a compact fluorescent bulb as our default energy picture.

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Testing code - on the testimonial cards on a single action page, you can't click to the testimonial page.

**Comment by frimpongopoku** [comment]
Will check that out ASAP

**Comment by frimpongopoku** [comment]
Also @BradHN1 , about the commented code, I always remove them when a new change is approved and  no new requests to go back to a previous design is made for a long time. You know how we like going back and forth on designs?? 🤣 🤣 🤣 . Yeah, I like to make things easy for myself 🤣 🤣 . So, this new batch of commented code will be removed when these additions are  shipped and everyone is happy with it for at least  3 weeks. 🤣 🤣

**Review by BradHN1 — APPROVED** [review]
Great work!  Sorry for the delay

**Pull request merged**
